import svg4everybody from 'svg4everybody';
import 'babel-polyfill';
import objectFitImages from 'object-fit-images';
import parallax from '../blocks/js-functions/parallax';
import mainSlider from '../components/main-slider/main-slider';
import addressCard from '../blocks/address-card/address-card';
import whereToBuy from '../components/whereToBuy/whereToBuy';
import map from '../components/map/map';
import newsCard from '../blocks/news-card/news-card';
import needHelp from '../components/needHelp/needHelp';
import burger from '../blocks/burger/burger';
// import modal from '../blocks/modal/modal';
import slider from '../blocks/slider/slider';
import productPopup from '../components/product-popup/product-popup';
import preloader from '../blocks/preloader/preloader';
import popups from '../blocks/popups/popups';
import products from '../components/products/products';
import tabs from '../blocks/tabs/tabs';
import order from '../components/order/order';
import cart from '../components/cart/cart';

const $ = window.$;

$(() => {
  svg4everybody();
  objectFitImages();
  parallax();
  mainSlider();
  addressCard();
  whereToBuy();
  map();
  newsCard();
  needHelp();
  burger();
  slider();
  // modal();
  productPopup();
  preloader();
  popups();
  products();
  tabs();
  order();
  cart();
});
